# Configuracion del analisis CI de SonarQube Cloud.
sonar.projectKey=karimadrico_tfg-azure-servicio-empresarial-seguro
sonar.organization=karimadrico
sonar.host.url=https://sonarcloud.io
sonar.sources=src,infra,scripts
sonar.tests=tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=src/test_local_api.py
sonar.terraform.provider.azure.version=3.100.0
