sonar.projectKey=karimadrico_tfg-azure-servicio-empresarial-seguro
sonar.organization=karimadrico
sonar.host.url=https://sonarcloud.io
sonar.projectName=TFG Azure Servicio Empresarial Seguro
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
sonar.exclusions=src/**/__pycache__/**,src/data/**
