trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  resourceGroup: rg-tfg-cloudautomation-dev
  location: northeurope

stages:
- stage: SecurityBaseline

  jobs:
  - job: ApplySecurity

    steps:

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'azure-service-connection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |

          echo "Applying tags..."

          az group update \
            --name $(resourceGroup) \
            --set tags.Environment=Development tags.Project=TFG

          echo "Enable Defender..."

          az security pricing create \
            --name VirtualMachines \
            --tier Standard

          echo "Assign RBAC..."

          az role assignment create \
            --assignee 73e3f106-2717-4bf0-81e3-f58b7a8cbe58 \
            --role Reader \
            --scope /subscriptions/a79fdf71-ae1e-4475-bebd-4a60a662e0ee/resourceGroups/$(resourceGroup)